import type { Metadata } from 'next'
import { Navigator } from '@/components'
import { Routes } from '@/utils/routes.list'

import './globals.css'


export const metadata: Metadata = {
  title: 'G 12',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="p-12 bg-indigo-400">
      <Navigator paths={ [Routes.HOME,Routes.CHARACTERES,Routes.ABOUT] }/>


        {children}
        
      </body>
    </html>
  )
}
